{
 "title": "Http Fibonacci",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Express Fibonacci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"express-app\", uri=\"/fibonacci\"}[1m]) / rate(http_server_requests_seconds_count{job=\"express-app\", uri=\"/fibonacci\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spring Fibonacci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"spring-boot-application\", uri=\"/fibonacci\"}[1m]) / rate(http_server_requests_seconds_count{job=\"spring-boot-application\", uri=\"/fibonacci\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Golang Fibonacci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"golang-app\", uri=\"/fibonacci\"}[1m]) / rate(http_server_requests_seconds_count{job=\"golang-app\", uri=\"/fibonacci\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}