scrape_configs:
  - job_name: "spring-boot-application"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ["spring-app:8080"]
    
  - job_name: "golang-app"
    metrics_path: "/metrics"
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ["golang-app:8081"]
    
  - job_name: "express-app"
    metrics_path: "/metrics"
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ["express-app:8082"]
    
  - job_name: "rust-app"
    metrics_path: "/metrics"
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ["rust-app:8083"]
